sys_name = "LaTeXTrans"
version = "0.1.0"
target_language = "ch"
source_language = "en"
paper_list = ['1703.10593']
tex_sources_dir = "L:\\A_Code\\Python_Code\\AI_Practical_Training\\LLM\\LLM-2\\data\\input"
output_dir = "L:\\A_Code\\Python_Code\\AI_Practical_Training\\LLM\\LLM-2\\data\\output"
category = {}
update_term = "False"
mode = 0
user_term = ""

[llm_config]
model = "deepseek-chat"
api_key = "sk-dbce8c36715e412a99fde80c9614661e"
base_url = "https://api.deepseek.com/chat/completions"